post http://localhost:5000/login
Content-Type: application/json

{

    
    "email":"ikiajja@gmail.com",
    "password":"123321"
    
}
###

POST  http://localhost:5000/users
Content-Type: application/json
{
    "name": "nana",
     "email":"nana@gmail.com",
    "password":"123321",
    "confPassword":"123321"
}
###

GET  http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJpa2lhamphIiwiZW1haWwiOiJpa2lhamphQGdtYWlsLmNvbSIsImlhdCI6MTY5MzI4OTk1NywiZXhwIjoxNjkzMzc2MzU3fQ.VKpI3kB6zU30ryyphYyWloBg7n3laTJEhzsaX0imN_g